---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

inputs:
- name: source-code
  path: .

outputs:
- name: image

caches:
- path: cache

run:
  path: build
