helm_repos:
  - name: stable
    repo_url: https://kubernetes-charts.storage.googleapis.com
  - name: concourse
    repo_url: https://concourse-charts.storage.googleapis.com/

helm_releases:
  - name: nginx-ingress
    chart: stable/nginx-ingress
    namespace: default
    release_values:
      controller:
        service:
          enableHttps: false
          ports:
            http: "{{ kind_port_mapping_host }}"
          nodePorts:
            http: "{{ kind_port_mapping_container }}"

  - name: concourse
    chart: concourse/concourse
    namespace: default
    release_values:
      secrets:
        localUsers: "{{ ci_user }}:{{ ci_pass }}"
      concourse:
        web:
          auth:
            mainTeam:
              localUser: "{{ ci_user }}"
          externalUrl: "http://{{ ci_host }}:{{ kind_port_mapping_host }}"
      web:
        ingress:
          enabled: true
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: "0m"
          hosts: ["{{ ci_host }}"]
      worker:
        replicas: 1

  - name: docker-registry
    chart: stable/docker-registry
    release_values:
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0m"
        hosts: ["{{ docker_host }}"]

  - name: chartmuseum
    chart: stable/chartmuseum
    release_values:
      env:
        open:
          DISABLE_API: false
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0m"
        hosts:
          - name: "{{ helm_host }}"
