helm_repos:
  - name: stable
    repo_url: https://kubernetes-charts.storage.googleapis.com
  - name: concourse
    repo_url: https://concourse-charts.storage.googleapis.com/

helm_releases:
  - name: nginx-ingress
    chart: stable/nginx-ingress
    namespace: default
    release_values:
      controller:
        service:
          nodePorts:
            http: "{{ kind_port_mapping_container }}"

  - name: concourse
    chart: concourse/concourse
    namespace: default
    release_values:
      secrets:
        localUsers: "demo:demo"
      concourse:
        web:
          auth:
            mainTeam:
              localUser: "demo"
          externalUrl: "http://{{ ci_host }}:{{ kind_port_mapping_host }}"
      web:
        ingress:
          enabled: true
          hosts: ["{{ ci_host }}"]
