- name: Create demo kubernetes environment
  hosts: localhost
  gather_facts: yes
  collections:
    - community.kubernetes

  roles:
    - { role: kind,          tags: ["kind"]                }

- name: Cleanup
  hosts: localhost
  gather_facts: no
  tasks:
    - name: delete kind cluster
      kind:
        name: "{{ kind_cluster_name }}"
        action: delete
      tags: [ never, cleanup ]
    - name: delete kind cluster config
      file:
        path: "{{ kind_cluster_config_path }}"
        state: absent
      tags: [ never, cleanup ]
