- name: Create demo kubernetes environment
  hosts: localhost
  gather_facts: yes
  collections:
    - community.kubernetes

  roles:
    - { role: kind,          tags: ["kind"]                }
    - { role: helm,          tags: ["helm"]                }

  tasks:
    - name: create /etc/hosts records
      become: yes
      lineinfile:
        path: /etc/hosts
        line: "{{ item.address }} {{ item.host }}"
        create: yes
      with_items: "{{ hosts_records }}"

- name: Cleanup
  hosts: localhost
  gather_facts: no
  tasks:
    - name: delete kind cluster
      kind:
        name: "{{ kind_cluster_name }}"
        action: delete
      tags: [ never, cleanup ]
    - name: delete kind cluster config
      file:
        path: "{{ kind_cluster_config_path }}"
        state: absent
      tags: [ never, cleanup ]
    - name: delete /etc/hosts records
      become: yes
      lineinfile:
        path: /etc/hosts
        line: "{{ item.address }} {{ item.host }}"
        state: absent
      with_items: "{{ hosts_records }}"
