name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ${{inputs.environment}}

    steps:

      - name: Perform Deployment
        run: |
          echo "Deploying to ${{inputs.environment}} ..."
          echo "using token ${{secrets.token}}"
