name: CD Pipeline

on:
  workflow_call:

jobs:
  deploy_dev:
    name: deploy
    uses: ./.github/workflows/deploy_env.yaml
    with:
      environment: dev

  deploy_staging:
    name: deploy
    uses: ./.github/workflows/deploy_env.yaml
    with:
      environment: staging

  deploy_live:
    name: deploy
    needs: deploy_staging
    uses: ./.github/workflows/deploy_env.yaml
    with:
      environment: live
