name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy_dev:
    name: ${{inputs.environment}}
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Trigger
        run: |
          echo "Deploying to ${{inputs.environment}}"
