name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
env:
  GH_TOKEN: ${{ github.token }}

permissions:
  contents: read
  deployments: write
  id-token: write

jobs:
  deploy:
    name: ${{inputs.environment}}
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Trigger
        run: |
          echo "Deploying to ${{inputs.environment}}"
          gh api repos/${{github.repository}}/deployments \
            -f "ref=${{ github.ref }}" \
            -f "environment=${{inputs.environment}}" \
            -f "auto_merge=false" \
            -f "description=Deploying ${{ github.ref }} to ${{inputs.environment}}" \
            -f "task=deploy"
