name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  deploy:
    name: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger
        run: |
          echo "Deploying to ${{inputs.environment}}"
          gh api repos/${{github.repository}}/deployments \
            -F "ref=${{ github.sha }}" \
            -F "environment=${{inputs.environment}}" \
            -F "auto_merge=false" \
            -F "description=Deploying ${{ github.sha }} to ${{inputs.environment}}" \
            -F "task=deploy" \
            -F "required_contexts[]"
